version: 2

models:
  - name: fct_sales
    description: "Tabela fato de vendas consolidada (Sales Header + Detail)."
    columns:
      - name: sales_order_id
        description: "Chave primária do pedido."
        tests:
          - not_null
      - name: fk_customer
        tests:
          - not_null
      - name: fk_product
        tests:
          - not_null
      - name: gross_amount
        description: "Valor Bruto (Quantidade * Preço Unitário)."

  - name: dim_customers
    description: "Dimensão de Clientes."
    columns:
      - name: sk_customer
        tests:
          - unique
          - not_null

  - name: dim_products
    description: "Dimensão de Produtos."
    columns:
      - name: product_sk
        tests:
          - unique
          - not_null

  - name: dim_sales_reason
    description: "Dimensão de Motivos de Venda."
    columns:
      - name: sk_sales
        tests:
          - unique
          - not_null